[[project]]
path = "."
version = "0.10.1"
assembler = "gas"
instruction_set = "arm"

[project.opts]
compiler = "clang"
compile_flags_txt = [
    "-target",
    "arm-none-eabi",
    "-mcpu=arm7tdmi",
]
diagnostics = true
default_diagnostics = false
